id: c260184b3fc94505af209c5a3ba4ef36
initial_creation_type: ocr
source_metadata:
  volumes:
    97a6c1aa5174410b9ce1a10e4066bcb5:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      volume_number: 18
