id: DD96D2433
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:48:17+00:00'
last_modified: '2022-05-26T10:21:17.844975+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    fd11:
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      order: 18
      base_file: fd11.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
